# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, develop ]
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox virtualenv flake8
      - name: Lint
        run: "tox -e flake8"

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - "ubuntu-py36"
          - "ubuntu-py37"
          - "ubuntu-py38"
          - "ubuntu-py39"
          - "ubuntu-pypy3"

          - "macos-py36"
          - "macos-py37"
          - "macos-py38"
          - "macos-py39"
          - "macos-pypy3"

          - "windows-py36"
          - "windows-py37"
          - "windows-py38"
          - "windows-py39"

        include:
          - name: "ubuntu-py36"
            python: "3.6"
            os: ubuntu-latest
            tox_env: "py36"
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
            tox_env: "py37"
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "py38"
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-latest
            tox_env: "py39"
          - name: "ubuntu-pypy3"
            python: "pypy3"
            os: ubuntu-latest
            tox_env: "pypy3"

          - name: "macos-py36"
            python: "3.6"
            os: macos-latest
            tox_env: "py36"
          - name: "macos-py37"
            python: "3.7"
            os: macos-latest
            tox_env: "py37"
          - name: "macos-py38"
            python: "3.8"
            os: macos-latest
            tox_env: "py38"
          - name: "macos-py39"
            python: "3.9"
            os: macos-latest
            tox_env: "py39"
          - name: "macos-pypy3"
            python: "pypy3"
            os: macos-latest
            tox_env: "pypy3"

          - name: "windows-py36"
            python: "3.6"
            os: windows-latest
            tox_env: "py36"
          - name: "windows-py37"
            python: "3.7"
            os: windows-latest
            tox_env: "py37"
          - name: "windows-py38"
            python: "3.8"
            os: windows-latest
            tox_env: "py38"
          - name: "windows-py39"
            python: "3.9"
            os: windows-latest
            tox_env: "py39"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 spade --count --ignore=E501 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 spade --count --exit-zero --max-complexity=10 --ignore=E501 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Run coverage
      run: |
        coverage erase
        coverage run --source=spade -m py.test
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test
    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS=${{ matrix.os }},PYTHON=${{ matrix.python }}
        file: ./coverage

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
